### ISSUE TITLE
Use this software to which version of the kernel ？？？

### ISSUE THREAD

**Issue by zhenyouluo** [rockchip-linux/gstreamer-rockchip#1]
I use release-4.4 the version of the kernel, no/dev/VPU-service

**Comment by geekerlw** [comment]
use the vpu-service-4.4 branch

**Comment by wzyy2** [comment]
We will release a version at the end of this month. Please wait.
Now all branches are not verified..

**Comment by zhenyouluo** [comment]
Thanks， Looking forward to

**Comment by karllmitchell** [comment]
Is there any chance you could add some sample gst-launch-1.0 commands for common functions using mpph264enc? I would like to try it out for transcoding MPEG-2 ts to h.264 MPEG-4.
