### ISSUE TITLE
Failed to load plugin '/usr/local/lib/gstreamer-1.0/libgstrockchipmpp.so': /usr/local/lib/gstreamer-1.0/libgstrockchipmpp.so: undefined symbol: gst_pad_get_task_state

### ISSUE THREAD

**Issue by arnstein** [rockchip-linux/gstreamer-rockchip#12]
I use a Firefly RK3399 board and have the Ubuntu image provided by Firefly. When running ./autogen.sh in the gstreamer-rockchip folder the output is as follows:

configure: *** Plug-ins with dependencies that will be built:
	rkximage
	rockchipmpp

configure: *** Plug-ins with dependencies that will NOT be built:
	vpudec

After make and make install, I try to launch a pipe with using mppvideodec as decoder. Gstreamer does not find the plugin. If I specify with --gst-plugin-path=/usr/local/lib/gstreamer-1.0/ I get the following message:

(gst-plugin-scanner:18102): GStreamer-WARNING **: Failed to load plugin '/usr/local/lib/gstreamer-1.0/libgstrockchipmpp.so': /usr/local/lib/gstreamer-1.0/libgstrockchipmpp.so: undefined symbol: gst_pad_get_task_state

How can I fix this?

**Comment by geekerlw** [comment]
gst_pad_get_task_state is a new api since gstreamer 1.12, so you need to upgrade your build env to the current version

**Comment by arnstein** [comment]
Thank you!
