### ISSUE TITLE
gstreamer-rockchip not working on arm64?

### ISSUE THREAD

**Issue by arnstein** [rockchip-linux/gstreamer-rockchip#13]
My rootfs is created following the README in https://github.com/rockchip-linux/rk-rootfs-build/. When building it with ARCH=armhf I can use both mppvideodec and mpph264enc, but when built with ARCH=arm64 gst-inspect-1.0 does not show these. How can I enable these with the arm64 architecture?

**Comment by hizukiayaka** [comment]
Don't use Debian, and it works fine on arm64(aarch64).

**Comment by arnstein** [comment]
What do you suggest that I use?

**Comment by hizukiayaka** [comment]
Have a try on OE or buildroot.
