### ISSUE TITLE
Installing plugins.

### ISSUE THREAD

**Issue by nuraldin** [rockchip-linux/gstreamer-rockchip#16]
Sorry in advance if my issue is too stupid.

Trying to install the plugins it doesn't find: the vpu legacy libraries, rockchip mpp libraries and drm/kms and x11 libraries. 

Please, could you help me understand why this could be?

However, thank you for all the work you have done. 
Best regards.

**Comment by hizukiayaka** [comment]
Don't open an issue for that. Ask the google.
