### ISSUE TITLE
mpp plugin for gstreamer crashing with subtitles

### ISSUE THREAD

**Issue by teacupx** [rockchip-linux/gstreamer-rockchip#17]
As the title describes, gstreamer will crash with segment violation when you are playing any video with subtitles. It will happen right when it tries to display the first subtitle. It happens with different gstreamer players (I tried with gst-play-1.0 and Parole). It also happens both when you use the rkximagesink or the Xv video sink.

**Comment by chwe17** [comment]
Closed mean you've fixed it? you've no idea how to fix it? Or you don't thing this is an issue at all?
