### ISSUE TITLE
failed to build on Ubuntu 16.04 arm64

### ISSUE THREAD

**Issue by numbqq** [rockchip-linux/gstreamer-rockchip#21]
I'm try to build gstreamer on Ubuntu 16.04 arm64, I refer to tutorial http://opensource.rock-chips.com/wiki_Mpp. 
Build command: `./autogen.sh --disable-rkximage && make`
But failed with error:
```
configure: Requested 'gstreamer-1.0 >= 1.12.0' but version of GStreamer is 1.8.3
configure: error: no gstreamer-1.0 >= 1.12.0 (GStreamer) found
  configure failed
```
It seems some dependecies issue. So how to build gstreamer on Ubuntu 16.04 arm64?

**Comment by nationalflag** [comment]
I encounter this error too. How to solve this?
