### ISSUE TITLE
how to configure build to find correct gstreamer 

### ISSUE THREAD

**Issue by nenadlazovic** [rockchip-linux/gstreamer-rockchip#23]
I am trying to build gstreamer-rockchip on AsusTinkerboard w OS 20180222-tinker-board-linaro-stretch-alip-v2.0.5.img.

I recompiled latest gstreamer 1.15 using cerbero (https://gstreamer.freedesktop.org/documentation/installing/building-from-source-using-cerbero.html#). Build generates dist/ in gstreamer-1.0/cerbero/build/dist/linux_armv7/*
It runs ok (of course without hardware acceleration).

When trying to compile gstreamer-rockchip, build can not find my gststreamer dist.

   root@tinkerboard:/home/linaro/gstreamer-rockchip# ./autogen.sh --disable-rkximage
   ...
   checking for GIO... yes
   checking for ORC... no
   checking for GST... no
   configure: No package 'gstreamer-1.0' found
   configure: error: no gstreamer-1.0 >= 1.12.0 (GStreamer) found
   configure failed

Questions: how to configure gstreamer-rockchip build to point to gstreamer dist ?

Thanks.

**Comment by chandong83** [comment]
Check the LD_LIBRARY_PATH System Environment.

LD_LIBRARY_PATH must be set to Path Gstreamer Libarary.

$ echo $LD_LIBRARY_PATH
and
$ export LD_LIBRARY_PATH=/usr/local/lib
or
$ export LD_LIBRARY_PATH=/usr/lib

**Comment by nenadlazovic** [comment]
chandong83,
I gave up on gstreamer cerbero build. I am using steps from your blog at https://blog.naver.com/PostList.nhn?blogId=chandong83

Following dependence are not available: libdirac-dev libschroedinger-dev libslv2-dev. 
Any suggestions ?

thanks

**Comment by chandong83** [comment]
Hi,

I share the PDF file. 
I installed it with this.
but, it is in Chinese.
you can read it in Google Translator. I saw that too.

Thank you.
[RK Linux Camera GStreamer PDF](http://blogattach.naver.net/d247ce7d6f3736eac52244724ea8d3ab0d5ca64791/20180502_183_blogfile/chandong83_1525231392704_b3cl10_pdf/RK_linux_camera_gstreamer_%3F%E9%C4%3F%3F_v1.0_20171212.pdf)

**Comment by nenadlazovic** [comment]
thank you. will try to follow document.

**Comment by chandong83** [comment]
can i have your email?
i will send it.

**Comment by nenadlazovic** [comment]
nlazovic@senorta.com

**Comment by nationalflag** [comment]
@chandong83 @nenadlazovic could you send the pdf to me? Thanks! 595421379@qq.com

**Comment by kcarriello** [comment]
I also need this PDF, could you please send it to me. klebercarriello@gmail.com

**Comment by chandong83** [comment]
> I also need this PDF, could you please send it to me. [klebercarriello@gmail.com](mailto:klebercarriello@gmail.com)

I uploaded it in the link below.
[https://github.com/chandong83/rockchips_docs/blob/master/RK_linux_camera_gstreamer_%E5%BA%94%E7%94%A8%E5%BC%80%E5%8F%91_v1.0_20171212.pdf](url)
