### ISSUE TITLE
mppvideodec caps, parsed

### ISSUE THREAD

**Issue by XunChangqing** [rockchip-linux/gstreamer-rockchip#29]
你好，
我检查videodec插件的sink pad caps，必须要parsed为true才行
rtph264depay ! mppvideodec
这样无法协商成功，必须
rtph264depay ! h264parse ! mppvideodec
才行，可以不使用h264parse吗？
因为这个parse还是有一些开销的。

**Comment by JeffyCN** [comment]
it's required, unless enable mpp's internal parsing, which might have worse performance.
