### ISSUE TITLE
这种问题是怎么回事？？？

### ISSUE THREAD

**Issue by yhsilience** [rockchip-linux/gstreamer-rockchip#30]
我使用自己写的qt播放器（Qmediaplayer） ，播放4k视频。gst 出现下面的错误信息
gstmppdecbufferpool.c:295:gst_mpp_dec_buffer_pool_acquire_buffer:<mppvideodec0:pool:src> error
mppvideodec gstmppvideodec.c:700:gst_mpp_video_dec_handle_frame:<mppvideodec0> can't process this frame

**Comment by JeffyCN** [comment]
cannot repro.
