### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by idreamerhx** [rockchip-linux/gstreamer-rockchip#31]
make[3]: Entering directory '/mnt/usbdisk/rockchip/gstreamer-rockchip/gst/vpudec'
  CC       libgstvpudec_la-gstvpu.lo
  CC       libgstvpudec_la-gstvpudec.lo
gstvpudec.c: In function 'gst_vpudec_sendeos':
gstvpudec.c:118:16: error: 'VPU_API_DEC_OUTPUT_EOS' undeclared (first use in this function); did you mean 'VPU_API_SET_OUTPUT_BLOCK'?
   pkt.nFlags = VPU_API_DEC_OUTPUT_EOS;
                ^~~~~~~~~~~~~~~~~~~~~~
                VPU_API_SET_OUTPUT_BLOCK
gstvpudec.c:118:16: note: each undeclared identifier is reported only once for each function it appears in
gstvpudec.c:123:42: error: 'VPU_API_DEC_GET_EOS_STATUS' undeclared (first use in this function); did you mean 'VPU_API_GET_EOS_STATUS'?
   vpu_codec_ctx->control (vpu_codec_ctx, VPU_API_DEC_GET_EOS_STATUS, &is_eos);
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                          VPU_API_GET_EOS_STATUS
gstvpudec.c: At top level:
gstvpudec.c:165:8: error: unknown type name 'VPU_VIDEO_CODINGTYPE'
 static VPU_VIDEO_CODINGTYPE
        ^~~~~~~~~~~~~~~~~~~~
gstvpudec.c: In function 'to_vpu_stream_format':
gstvpudec.c:169:12: error: 'VPU_VIDEO_CodingAVC' undeclared (first use in this function); did you mean 'OMX_RK_VIDEO_CodingAVC'?
     return VPU_VIDEO_CodingAVC;
            ^~~~~~~~~~~~~~~~~~~
            OMX_RK_VIDEO_CodingAVC
gstvpudec.c:172:12: error: 'VPU_VIDEO_CodingHEVC' undeclared (first use in this function); did you mean 'OMX_RK_VIDEO_CodingHEVC'?
     return VPU_VIDEO_CodingHEVC;
            ^~~~~~~~~~~~~~~~~~~~
            OMX_RK_VIDEO_CodingHEVC

**Comment by JeffyCN** [comment]
mpp version not match
