### ISSUE TITLE
Could not open DRM module (NULL)

### ISSUE THREAD

**Issue by sdarktemplar** [rockchip-linux/gstreamer-rockchip#32]
Hi I launch this command 
"gst-launch-1.0 videotestsrc ! kmssink"
and got these error message

Setting pipeline to PAUSED ...
ERROR: Pipeline doesn't want to pause.
ERROR: from element /GstPipeline:pipeline0/GstKMSSink:kmssink0: Could not open DRM module (NULL)
Additional debug info:
gstkmssink.c(709): gst_kms_sink_start (): /GstPipeline:pipeline0/GstKMSSink:kmssink0:
reason: No such file or directory (2)
Setting pipeline to NULL ...
Freeing pipeline ...

Do I miss anything? thanks

**Comment by JeffyCN** [comment]
not belong to this repository.  but generally try to kill all the other display services
