### ISSUE TITLE
GStreamer 1.14.2 & Tinker Board

### ISSUE THREAD

**Issue by mndar** [rockchip-linux/gstreamer-rockchip#34]
For some reason, I am not able to get GStreamer functionality working on my Tinker Board
I am building a Gentoo rootfs.
Following are the errors

**rkximagesink**
------------------------------------------------------------------------------------
$ gst-launch-1.0 videotestsrc ! rkximagesink

Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...

** (gst-launch-1.0:26892): CRITICAL **: gst_dmabuf_memory_get_fd: assertion 'gst_is_dmabuf_memory (mem)' failed
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock

** (gst-launch-1.0:26892): CRITICAL **: gst_dmabuf_memory_get_fd: assertion 'gst_is_dmabuf_memory (mem)' failed
^Chandling interrupt.
Interrupt: Stopping pipeline ...
Execution ended after 0:00:00.742897209
Setting pipeline to PAUSED ...
---------------------------------------------------------------------------------
** H264 Video decoding **

# GST_DEBUG=3 gst-launch-1.0 rtspsrc location="rtsp://10.168.1.64:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1" user-id=admin user-pw=pass ! rtph264depay ! h264parse ! mppvideodec ! rkximagesink

Setting pipeline to PAUSED ...
mpi: mpp version: 723ee1e author: Herman Chen [legacy]: Fix 4.4 rkffplayer compatible issue
Pipeline is live and does not need PREROLL ...
Progress: (open) Opening Stream
Progress: (connect) Connecting to rtsp://10.168.1.64:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
Progress: (open) Retrieving server options
Progress: (open) Retrieving media info
Progress: (request) SETUP stream 0
Progress: (open) Opened Stream
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Progress: (request) Sending PLAY request
Progress: (request) Sending PLAY request
0:00:00.688027376 17050 0xb4a09f80 FIXME                default gstutils.c:3963:gst_pad_create_stream_id_internal:<fakesrc0:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
Progress: (request) Sent PLAY request
0:00:00.776004834 17050 0x815b7230 FIXME           videodecoder gstvideodecoder.c:933:gst_video_decoder_drain_out:<mppvideodec0> Sub-class should implement drain()
0:00:00.776126751 17050 0x815b7230 FIXME               basesink gstbasesink.c:3145:gst_base_sink_default_event:<rkximagesink0> stream-start event without group-id. Consider implementing group-id handling in the upstream elements
hal_h264d_api: hal_h264d_init mpp_buffer_group_get_internal used ion In
mpp_rt: found ion allocator
mpp_rt: found drm allocator
mpp_rt: found drm allocator in dts
0:00:00.809796751 17050 0x815b7230 FIXME           videodecoder gstvideodecoder.c:933:gst_video_decoder_drain_out:<mppvideodec0> Sub-class should implement drain()
mpp: deprecated block control, use timeout control instead

** (gst-launch-1.0:17050): CRITICAL **: gst_mpp_allocator_start: assertion 'size != 0' failed
0:00:00.810943584 17050 0x815b7230 ERROR       mppdecbufferpool gstmppdecbufferpool.c:112:gst_mpp_dec_buffer_pool_start:<mppvideodec0:pool:src> we received 0 buffer, we want at least 22
0:00:00.811013584 17050 0x815b7230 ERROR             bufferpool gstbufferpool.c:564:gst_buffer_pool_set_active:<mppvideodec0:pool:src> start failed
0:00:00.811115667 17050 0x815b7230 ERROR            mppvideodec gstmppvideodec.c:663:gst_mpp_video_dec_handle_frame:<mppvideodec0> Unable to activate the pool
0:00:00.811214834 17050 0x815b7230 ERROR            mppvideodec gstmppvideodec.c:693:gst_mpp_video_dec_handle_frame:<mppvideodec0> can't process this frame
mpp: deprecated block control, use timeout control instead

(gst-launch-1.0:17050): GStreamer-CRITICAL **: gst_caps_is_equal: assertion 'GST_IS_CAPS (caps1)' failed

-------------------------------------------------------

What am I doing incorrectly?

Regards
Mandar Joshi

**Comment by JeffyCN** [comment]
should be fixed.
