### ISSUE TITLE
mppvideodec不能设置为GST_STATE_NULL状态

### ISSUE THREAD

**Issue by CoolVenkee** [rockchip-linux/gstreamer-rockchip#35]
使用如下流水线开始播放OK
`rtspsrc location=your location ! rtph264depay ! h264parse ! mppvideodec ! fakesink`
但是对整条流水线设置为GST_STATE_NULL状态，mpp会报如下错误，有没有解决办法
`(test_gst_state:9514): GStreamer-CRITICAL **: gst_caps_is_strictly_equal: assertion 'GST_IS_CAPS (caps1)' failed
** (test_gst_state:9514): CRITICAL **: gst_video_codec_state_unref: assertion 'state->ref_count > 0' failed
0:00:09.116408588  9514 0xad2022c0 DEBUG            mppvideodec gstmppvideodec.c:515:gst_mpp_video_dec_handle_frame:<videodec> Handling frame 22
0:00:09.116590588  9514 0xad2022c0 ERROR            mppvideodec gstmppvideodec.c:687:gst_mpp_video_dec_handle_frame:<videodec> send packet failed -1002`

**Comment by simonchen007** [comment]
does that problem resovled yet ?

**Comment by JeffyCN** [comment]
should be fixed.
