### ISSUE TITLE
mppvideodec无法解析RTSP流

### ISSUE THREAD

**Issue by Rereflyer** [rockchip-linux/gstreamer-rockchip#36]
你好，执行mpp_platform_test显示板子的基本信息如下：
mpp_plat_test: chip name: rockchip,rk3399-eaidk-mipi rockchip,rk3399
mpp_plat_test: 
mpp_plat_test: chip vcodec type 00000202
mpp_plat_test: found vpu2 codec
mpp_plat_test: found rkvdec decoder
mpp_plat_test: 
mpp_plat_test: start probing decoder device name:
mpp_plat_test: H.264 decoder: /dev/rkvdec
mpp_plat_test: H.265 decoder: /dev/rkvdec
mpp_plat_test: MJPEG decoder: /dev/vpu_service
mpp_plat_test: VP9   decoder: /dev/rkvdec
mpp_plat_test: avs   decoder: /dev/vpu_service
mpp_plat_test: 
mpp_plat_test: start probing encoder device name:
mpp_plat_test: H.264 encoder: /dev/vpu_service
mpp_plat_test: H.265 encoder: /dev/vpu_service
mpp_plat_test: MJPEG encoder: /dev/vpu_service
mpp_plat_test: mpp platform test done

我们执行以下pipeline，gst-launch-1.0 rtspsrc location=rtsp://172.17.0.167:80/ch0_0.264 ! rtph264depay ! h264parse ! mppvideodec ! videoconvert ! ximagesink，会报错，打印信息如下：
Setting pipeline to PAUSED ...
mpi: mpp version: 203ff53 author: Herman Chen [test]: Fix not enough buffer on YUV444 jpeg decode
Pipeline is live and does not need PREROLL ...
Progress: (open) Opening Stream
Progress: (connect) Connecting to rtsp://172.17.0.167:80/ch0_0.264
Progress: (open) Retrieving server options
Progress: (open) Retrieving media info
Progress: (request) SETUP stream 0
Progress: (request) SETUP stream 1
Progress: (open) Opened Stream
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Progress: (request) Sending PLAY request
Progress: (request) Sending PLAY request
Progress: (request) Sent PLAY request
hal_h264d_api: set_mode=0, hw_spt=00000202, use_mode=1
mpp_rt: NOT found ion allocator
mpp_rt: found drm allocator
mpp: deprecated block control, use timeout control instead

** (gst-launch-1.0:3415): CRITICAL **: 02:49:55.273: gst_mpp_allocator_start: assertion 'size != 0' failed
mpp: deprecated block control, use timeout control instead

(gst-launch-1.0:3415): GStreamer-CRITICAL **: 02:49:55.274: gst_caps_is_equal: assertion 'GST_IS_CAPS (caps1)' failed

** (gst-launch-1.0:3415): CRITICAL **: 02:49:55.274: gst_mpp_allocator_start: assertion 'size != 0' failed
mpp: deprecated block control, use timeout control instead

(gst-launch-1.0:3415): GStreamer-CRITICAL **: 02:49:55.274: gst_caps_is_equal: assertion 'GST_IS_CAPS (caps1)' failed

** (gst-launch-1.0:3415): CRITICAL **: 02:49:55.275: gst_mpp_allocator_start: assertion 'size != 0' failed
mpp: deprecated block control, use timeout control instead

但是，如果我们改成H265的源，执行pipeline如下：
gst-launch-1.0 rtspsrc location=rtsp://172.17.0.167:80/ch0_0.265 ! rtph265depay ! h265parse ! mppvideodec ! videoconvert ! ximagesink，就不会有任何问题

请问我可以从哪方面入手来解决这个问题？谢谢！

**Comment by JeffyCN** [comment]
cannot repro
