### ISSUE TITLE
mppjpegdec causes offset in UV planes

### ISSUE THREAD

**Issue by Adam-Langley** [rockchip-linux/gstreamer-rockchip#41]
I am running latest source code of mpp and gstreamer-rockchip, and capturing mjpeg streams from a camera always result in UV planes being offset by 16 rows.

To demonstrate all the steps and prove where the failure is:

1. Capture a single jpeg from the camera, no decoding is performed, it's placed straight into a file. You can see the camera produces correct color planes.

**Command:**
`gst-launch-1.0 v4l2src device=/dev/video4 do-timestamp=true num-buffers=1 ! image/jpeg,width=1920,height=1080,framerate=25/1 ! jpegparse ! filesink location=camera.jpg`

**Output:** 
![camera](https://user-images.githubusercontent.com/16373742/50462202-8e8a4600-09e8-11e9-9a2f-e0f38233e3f7.jpg)

2. Decode the same frame using mpp into NV12 

**Command:**
`gst-launch-1.0 filesrc location=camera.jpg ! jpegparse ! mppjpegdec ! filesink location=camera.nv12`

**Output:** 
[camera.nv12.zip](https://github.com/rockchip-linux/gstreamer-rockchip/files/2711196/camera.nv12.zip)

3. Encode the raw NV12 file using software jpeg encoder to view the bad planes (specifically, notice the bleed on the red bag on the table. It's off by exactly 16 rows)

**Command:**
`gst-launch-1.0 filesrc location=camera.nv12 blocksize=$((1920*1080*2)) num-buffers=1 ! video/x-raw,format=NV12,width=1920,height=1080,framerate=1/1 ! jpegenc ! filesink location=camera_nv12.jpg`

**Output**
![camera_nv12](https://user-images.githubusercontent.com/16373742/50462237-cb563d00-09e8-11e9-8e5f-ff480d944ed0.jpg)

Now, decode the same raw camera frame using software, and back to JPG to see that it can be transcoded without upsetting UV.

1. Decode camera frame using software, to I420

**Command:**
`gst-launch-1.0 filesrc location=camera.jpg ! jpegparse ! jpegdec ! filesink location=camera_jpg.i420`

**Output**
[camera_jpg.i420.zip](https://github.com/rockchip-linux/gstreamer-rockchip/files/2711203/camera_jpg.i420.zip)

2. Encode the frame to JPG

**Command:**
`gst-launch-1.0 filesrc location=camera_jpg.i420 blocksize=$((1920*1080*2)) num-buffers=1 ! video/x-raw,format=I420,width=1920,height=1080,framerate=1/1 ! jpegenc ! filesink location=camera_i420.jpg`

**Output**
![camera_i420](https://user-images.githubusercontent.com/16373742/50462283-140df600-09e9-11e9-9bd5-042e43fc683a.jpg)

Finally, just to prove that the problem is mppjpegdec, and not the underlying mpp hardware - decode the raw JPG frame using the mpp test suite to NV12 - this will show a correct JPG

1. using decoder test, decode camera JPG

**Command:**
`mpi_dec_test -i camera.jpg -w 1920 -h 1080 -t 8 -o camera_mpp.nv12`

**Output*:*
[camera_mpp.nv12.zip](https://github.com/rockchip-linux/gstreamer-rockchip/files/2711207/camera_mpp.nv12.zip)

2. Using MPP, encode this back to a JPG

**Command:**
`mpi_enc_test -d 1 -i camera_mpp.nv12 -w 1920 -h 1080 -t 8 -o camera_mpp.jpg`

**Output:**
![camera_mpp](https://user-images.githubusercontent.com/16373742/50462467-61d72e00-09ea-11e9-89e4-d516769023a1.jpg)

**Comment by JeffyCN** [comment]
that is expected, the hardware will align the strides to 16, and this info is stored in the gst video info(same as mppvideodec).

and for the mpp test, it would remove the extra bytes when writing to file.
