### ISSUE TITLE
cannot initialize work tree for gstreamer-rockchip

### ISSUE THREAD

**Issue by avp24** [rockchip-linux/gstreamer-rockchip#47]
I am trying to install rockchip linux sdk by following steps mentioned in below link:
http://opensource.rock-chips.com/wiki_Source

Now after giving below command:
../repo/repo sync -f -j10
I am facing below error:
error.GitError: cannot initialize work tree for gstreamer-rockchip

tried to clean Up everything and re-install again but facing same error.

**Comment by yash4ever** [comment]
I am trying to buildroot image in my ubuntu 16.04 for  RK3328  i am following

http://opensource.rock-chips.com/wiki_Linux_user_guide

and encountering sync error 

 * [new branch]      master     -> rockchip-linux/master
Fetching projects:  65% (17/26)7), 8.96 MiB | 439.00 KiB/s   
fatal: Couldn't find remote ref refs/heads/rkvideo.00 KiB/s   /s   
error: Cannot fetch gstreamer-rockchip from https://github.com/rockchip-linux/gstreamer-rockchip


    result = cmd.Execute(copts, cargs)
  File "/home/yash/KEPU/repo/subcmds/sync.py", line 855, in Execute
    project.Sync_LocalHalf(syncbuf, force_sync=opt.force_sync)
  File "/home/yash/KEPU/repo/project.py", line 1380, in Sync_LocalHalf
    self._InitWorkTree(force_sync=force_sync, submodules=submodules)
  File "/home/yash/KEPU/repo/project.py", line 2594, in _InitWorkTree
    raise GitError("cannot initialize work tree for " + self.name)
error.GitError: cannot initialize work tree for gstreamer-rockchip

**Comment by JeffyCN** [comment]
There's no rkvideo branch here, guess the manifests are out-dated.

Better to use latest release manifests, e.g. rk3399_linux_release.xml/rk3288_linux_release.xml...
