### ISSUE TITLE
Freezing of my gst player after looping

### ISSUE THREAD

**Issue by jr1234567890** [rockchip-linux/gstreamer-rockchip#48]
Hi. I am seeing some crashing/lockup problems when coding with the gst media kit in C.

I have coded a simple c video player that loops, and I am getting lockups 20
to 700 minutes into each run.

Configuration:
Hardware: Rock64, 4GB board
OS: Latest Bionic for Rock64, downloaded from: www.armbian.com/rock64/
   Armbian_5.90_Rock64_Ubuntu_bionic_default_4.4.182_desktop.img
Media kit with gstreamer 1.14, ported to the GPU for the Rock64
   https://forum.armbian.com/topic/9310-rk3328-media-script-rock64-renegade
Video: Big Bunny 1080p, 30fps, h264 from
http://bbb3d.renderfarming.net/download.html 

And, as I said, at some random time, the video freezes, showing a single
image.  It runs full screen, so I need to SSH into it to kill the processes.

When turning on GST_DEBUG=2, I get a bunch of warnings and error messages,
but the video launches and plays fine, and loops fine.
A log file is attached.
I've also run at GST-DEBUG=3 and 4, but it never crashes at the same time. 
Sometimes it is during a seek to 0 (with the GST log message stopping in mid
sentence), sometimes it is in the middle of the normal playback.

Note that I do see an error message every few minutes.  This also seems
random, spaced 1 to 10 minutes apart.
0x7f7c06a4a0 ERROR mppvideodec
gstmppvideodec.c:693:gst_mpp_video_dec_handle_frame:<mppvideodec0>
I see no visible artifacts while the video is playing.

Is there a fix for this kind of freezing issue?  Is this
a common issue with gstreamer apps?   
[simple_gst_player_ debug.zip](https://github.com/rockchip-linux/gstreamer-rockchip/files/3444987/simple_gst_player_.debug.zip)

**Comment by JeffyCN** [comment]
seems to be fixed, please re-open if repro with newest version.
