### ISSUE TITLE
ERROR:gstmppvideoenc.c:115:gst_mpp_video_enc_stop:assertion failed:

### ISSUE THREAD

**Issue by godtell** [rockchip-linux/gstreamer-rockchip#49]
我们在使用3399pro开发板进行rtsp推流时，可以正常的推送rstp流，但当对方停止获取视频流时每次都报以下的错误（有时一启动就报该错），使程序直接挂掉
ERROR:gstmppvideoenc.c:115:gst_mpp_video_enc_stop:assertion failed:(g)atomic_int_get(...)==FALSE
每次停止时都报错，有时候启动时还没有开始推流时也会报这个错。
能看看这个问题吗？谢谢！

**Comment by JeffyCN** [comment]
fixed
