### ISSUE TITLE
Horizontal image shift, when using opencv with rkisp pipeline

### ISSUE THREAD

**Issue by AlexKaravaev** [rockchip-linux/gstreamer-rockchip#55]
Almost every tenth of the image I take from opencv are having strange horizontal shift. 

I am not sure, that problem is in code, because as you can see from attached images, with v4l pipeline the images is not shifted though has color issues. 

This is pipeline that I am using
```'rkisp device='+self.preview_devs[index]+' io-mode=4 ! video/x-raw,format=NV12,width='+str(self.cam_width)+',height='+str(self.cam_height)+',framerate=15/1 ! videoconvert ! appsink'```

With rkisp
https://imgur.com/EqIjgsO
With v4l
https://imgur.com/GxDCquT

**Comment by JeffyCN** [comment]
rkisp is not here(gstreamer-rockchip).

and rkisp is outdated, we are using v4l2src + remote 3A server now.

about shifts, might due to hardware limits, for example we store the strides info in the gst video info, and honor it in the sinks(e.g. rkximagesink/kmssink...)
