### ISSUE TITLE
Maintainer E-Mail address invalid

### ISSUE THREAD

**Issue by stylesuxx** [rockchip-linux/gstreamer-rockchip#57]
According to the meta data the maintainer is:
`Randy Li <randy.li@rock-chips.com>`

Unfortunately the mail server returns:
`550 randy.li@rock-chips.com:user not exist`

Please update accordingly so the maintainer can be contacted if needed.

**Comment by JeffyCN** [comment]
Randy is no longer working here...

This is actually a company project, we don't have a specific maintainer now, just "hey, here's a bug, who got time to fix it!" ;)

It seems like i'm the only one who has an interest in it now(Francis Fan left Rockchip recently too)
