### ISSUE TITLE
Qt+gstreamer+mpp  play video file long time will be stuck at mpp get_frame

### ISSUE THREAD

**Issue by jasonwxj2009** [rockchip-linux/gstreamer-rockchip#67]
Hi,
I use Qt + gstreamer+mpp to play video continuously， about 4 hour later  （sometimes less than ），video will stuck，code at mpp.cpp:l326  :
MPP_RET Mpp::get_frame(MppFrame *frame):
`
 if (mOutputTimeout < 0) {
                /* block wait */
                mFrames->wait();
`
Qt application is dead lock , should be restart!
Is there any solution？

**Comment by JeffyCN** [comment]
Might be this issue:
https://github.com/JeffyCN/rockchip_mirrors/commit/21de0626303055cc31c3836170c13b1d17efc7c3
