### ISSUE TITLE
About rk3308 videosink

### ISSUE THREAD

**Issue by Yann-Song** [rockchip-linux/gstreamer-rockchip#72]
Hi:
     which video sink is used for rk3308 ?  I build sdk but with no video sink, Here is my gstreamer's log: 

     gst-launch-1.0  uridecodebin uri="file:///userdata/media/comp.mp4" ! autovideosink 
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
WARNING: from element /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0: Resource not found.
Additional debug info:
gstautodetect.c(348): gst_auto_detect_find_best (): /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0:
Failed to find a usable video sink
Redistribute latency...
Redistribute latency...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Got EOS from element "pipeline0".
Execution ended after 0:00:12.510052381
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...

**Comment by JeffyCN** [comment]
There are multiple video sink could be used, but that depends on which display service you are using.
Normally the rockchip buildroot SDK(with wayland display service) should support:
waylandsink kmssink glimagesink fakesink filesink fpsdisplaysink, .etc

For debian X11 sdk:
xvimagesink rkximagesink kmssink glimagesink ximagesink fakesink filesink fpsdisplaysink, .etc

Anyway, that's more about the system environment, and i don't think it has anything to do with gstreamer-rockchip....

**Comment by Yann-Song** [comment]
Thank you !
    With use wayland or kmssink will cause oom, since rk3308 only  64M ddr.

**Comment by JeffyCN** [comment]
well, that things indeed require lots of memory(dma) :(

maybe you can try fbdevsink, or write your own appsink and output to /dev/fb0

**Comment by Yann-Song** [comment]
Ok , I will try it , thank you
