### ISSUE TITLE
Latest source code cannot BUILD

### ISSUE THREAD

**Issue by thanh311078** [rockchip-linux/gstreamer-rockchip#75]
git clone https://github.com/rockchip-linux/gstreamer-rockchip.git
./autogen.sh
./configure
make

ERRORS:
gstmppvideoenc.h:80:3: error: unknown type name ‘MppEncHeaderMode’
gstmppvideoenc.c:97:7: error: unknown type name ‘MppEncHeaderMode’; did you mean ‘MppEncSeiMode’?
gstmppvideoenc.c:232:3: error: unknown type name ‘MppEncCfg’; did you mean ‘MppEncHwCfg’?
...
I try to search in source code and not see the MppEncHeaderMode, MppEncCfg... definition, may be missing the file?

**Comment by thanh311078** [comment]
Sorry, need lastest mpp :-))

**Comment by coflery** [comment]
> 抱歉，需要最新的MPP :-)）
good job.
Me too.

**Comment by willosonico** [comment]
how did you solve this? i still get the error

**Comment by fghoussen** [comment]
Same problem. New to rockchip : what is mpp? How to update it?

**Comment by fghoussen** [comment]
Will give a try to https://github.com/rockchip-linux/mpp
