### ISSUE TITLE
undefined symbol: mpp_enc_cfg_set_u32

### ISSUE THREAD

**Issue by marstears** [rockchip-linux/gstreamer-rockchip#80]
Hi I have a problem here when I was trying to use compiled plugins.
Hardware: Tinkerboard S
OS: Armbian
Gstreamer version: 1.14.4
Core GStreamer libraries version: 1.14.4-1
GStreamer libraries base version: 1.14.4-2
GCC version: 8.3.0

I successful build and install rkximage and rockchipmpp in /usr/local/lib/gstreamer-1.0/.
But when I use gst-inspect:
```
gst-inspect-1.0 --gst-plugin-path=/usr/local/lib/gstreamer-1.0/
(gst-plugin-scanner:13721): GStreamer-WARNING **: 11:46:01.452: Failed to load plugin '/usr/local/lib/gstreamer-1.0/libgstrockchipmpp.so': /usr/local/lib/gstreamer-1.0/libgstrockchipmpp.so: undefined symbol: mpp_enc_cfg_set_u32
rkximage:  rkximagesink: Video sink
```
It looks like the rkximage plugin is normal, but rockchipmpp got a undefined symbol error and put into plugin blacklist.
After doing some research I still can not fined a solution. Please help me, thanks.

**Comment by JeffyCN** [comment]
mpp_enc_cfg_set_u32 should come from mpp, so try the newest mpp or the one with closest commit date.
