### ISSUE TITLE
关于 rkximagesink 中的 colorkey 使用问题

### ISSUE THREAD

**Issue by gang929** [rockchip-linux/gstreamer-rockchip#83]
**请问在使用  rkximagesink 插件进行视频播放时，窗口会有重叠的问题。**

当前RK3288所使用的的系统是debian 9， kernel版本是4.4.154， xorg 1.19.2-1.

在RK3288盒子上，使用命令 `gst-launch-1.0 uridecodebin uri=file:///root/a.mp4 ! rkximagesink` 来播放一个MP4视频，通过命令输出可以看到已启用了mpp进行硬件解码，并且视频也能正常播放。但存在窗口重叠问题。即，当视频正在播放时，如果将另一个普通窗口拖到该视频窗口上，视频窗口的标题栏部分正常被遮挡，但视频部分一直处于最顶层。

通过查询 rkximagesink 的更新日志，发现该问题已在  `https://github.com/rockchip-linux/gstreamer-rockchip/commit/0bd9984e4429a54b02ce5673fdc68410dd2c9ada` 中已解决。

但在该盒子上更新了新的gstreamer-rockchip plugin，问题仍然存在。

通过drm API，获取到的 plane（DRM_PLANE_TYPE_PRIMARY） 属性中只有`prop_name type
prop_name FB_ID
prop_name CRTC_ID
prop_name CRTC_X
prop_name CRTC_Y
prop_name CRTC_W
prop_name CRTC_H
prop_name SRC_X
prop_name SRC_Y
prop_name SRC_W
prop_name SRC_H
prop_name SHARE_ID
prop_name ZPOS
prop_name FEATURE
prop_name EOTF
prop_name COLOR_SPACE
prop_name GLOBAL_ALPHA
prop_name BLEND_MODE` 不包含  colorkey。

请问该 rkximagesink: Support colorkey commit 是否需要对应相应的linux kernel版本？  应该如何查找该kernel是否支持这 colorkey 功能？

**Comment by JeffyCN** [comment]
it's a new feature supported officially in BSP kernel 4.19 for vop2 hardware(rk356x chips for now) by "Andy Yan <andy.yan@rock-chips.com>"

maybe you can ask Andy if it's possible to add it for 3288 too.
