### ISSUE TITLE
mpph264enc image corruption

### ISSUE THREAD

**Issue by rw-vemotion** [rockchip-linux/gstreamer-rockchip#86]
I used the command below to generate a test stream after trying to work around an issue observed when encoding.
**`gst-launch-1.0 videotestsrc num-buffers=512 ! video/x-raw,format=NV12,width=1920,height= 1080,framerate=30/1 ! queue ! mpph264enc ! queue ! h264parse ! mpegtsmux ! filesink location=./2k.ts`**

I issued the command on a ROC-RK3566-PC from Firefly and then copied the resultant file to my Intel machine for playback using vlc / ffplay. The stream exhibits a green line across the bottom few (probably 8) lines of the image.

This partly confirms an issue we have been observing, without having to create any special test code.
During our investigations, we have found that the encoder does not appear to respect/use the memory offsets within a video buffer. That is to say we wrap separate GstMemory blocks for Y and UV planes and the associated GstVideoInfo structure is provided with an offset for the UV plane equal to the size of the Y plane data. This code works fine on other platforms, but for Rockchip, this leads to the colour planes corruption. Our workaround has been to over-allocate the memory used for the planes and adjust the Y plane size and offset for the UV plane to equal `Y-stride x adjustedHeight` (where adjustedHeight = frameHeight rounded up to the nearest 16). For 1920x1080, adjustedHeight would be 1088 rather than 1080.

**Comment by JeffyCN** [comment]
it's a knowing issue, which is already fixed. this github repo is no longer updated due to compony policy :(

please check this mirror for newest version:
https://github.com/JeffyCN/rockchip_mirrors/tree/gstreamer-rockchip
